services:
# Mandatory services
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    restart: on-failure
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - wordpress

# Bonus services
  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    restart: on-failure
    env_file: .env
    networks:
      - inception
    depends_on:
      - mariadb

  vsftpd:
    container_name: vsftpd
    build: ./requirements/bonus/vsftpd
    restart: on-failure
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - 21:21
      - 42000-42010:42000-42010
    networks:
      - inception
    depends_on:
      - wordpress

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    restart: on-failure
    env_file: .env
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - inception
    privileged: true

  website:
    container_name: website
    build: ./requirements/bonus/website
    restart: on-failure
    env_file: .env
    networks:
      - inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/mariadb
      # device: /home/drontome/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../volumes/wordpress
      # device: /home/drontome/data/wordpress

networks:
  inception:
    driver: bridge
